### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [LUOyk1999/NodeID#1]
Hello! I am very interested in your impressive and amazing work after reading your paper!
I wonder when will you release your source code because it seems amazing!

Thank you!

**Comment by LUOyk1999** [comment]
Thank you for your support of our work. Our paper is currently under review, so it is not convenient to make the code public at this time. If our paper is fortunate enough to be accepted, we will immediately release the code. For now, I can send you a toy example of the code to try out this method. Would that be acceptable to you?
